// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ar

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"slices"
	"strings"

	"github.com/invopop/gobl.html/components/t"
	"github.com/invopop/gobl/addons/ar/arca"
	"github.com/invopop/gobl/bill"
	"github.com/invopop/gobl/cbc"
	"github.com/invopop/gobl/num"
	"github.com/invopop/gobl/tax"
)

// ar-arca-tax-type codes counted towards each amount of the fiscal
// transparency block. Codes 1 (national) and 4 (internal) are national
// indirect taxes; code 3 covers municipal taxes, which provinces and
// municipalities are invited to disclose under the same regime.
var (
	transparencyNationalTaxTypes  = []cbc.Code{"1", "4"}
	transparencyMunicipalTaxTypes = []cbc.Code{"3"}
)

// ARCAFiscalTransparency renders the "Régimen de Transparencia Fiscal al
// Consumidor" block required by Ley 27.743 and ARCA RG 5614/2024 on Class B
// (final consumer) documents. The labels are legal text fixed by the
// resolution and are intentionally not translated.
func ARCAFiscalTransparency(inv *bill.Invoice) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if ft := newFiscalTransparency(inv); ft != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"arca-transparency\"><h2>Régimen de transparencia fiscal al consumidor (Ley 27.743)</h2><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(ft.line(ctx))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/regimes/ar/transparency.templ`, Line: 33, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// fiscalTransparency holds the amounts shown in the transparency block.
// otherNational and municipal are nil when the invoice carries no charges
// of the matching tax types, in which case the label is omitted.
type fiscalTransparency struct {
	vat           num.Amount
	otherNational *num.Amount
	municipal     *num.Amount
}

// line composes the single sentence with each label and its amount.
func (ft *fiscalTransparency) line(ctx context.Context) string {
	parts := []string{
		"IVA Contenido: " + t.LocalizeMoney(ctx, ft.vat),
	}
	if ft.otherNational != nil {
		parts = append(parts, "Otros impuestos nacionales indirectos: "+t.LocalizeMoney(ctx, *ft.otherNational))
	}
	if ft.municipal != nil {
		parts = append(parts, "Impuestos municipales: "+t.LocalizeMoney(ctx, *ft.municipal))
	}
	return strings.Join(parts, ". ") + "."
}

func newFiscalTransparency(inv *bill.Invoice) *fiscalTransparency {
	if inv == nil || inv.Tax == nil || inv.Totals == nil {
		return nil
	}
	dt := cbc.Code(inv.Tax.Ext.Get(arca.ExtKeyDocType).String())
	if !slices.Contains(arca.DocTypesB, dt) {
		return nil
	}
	ft := &fiscalTransparency{
		vat: containedVAT(inv.Totals.Taxes),
	}
	ft.otherNational = sumTaxCharges(inv.Charges, transparencyNationalTaxTypes)
	ft.municipal = sumTaxCharges(inv.Charges, transparencyMunicipalTaxTypes)
	return ft
}

func containedVAT(tt *tax.Total) num.Amount {
	vat := num.MakeAmount(0, 2)
	if tt == nil {
		return vat
	}
	for _, cat := range tt.Categories {
		if cat.Code != tax.CategoryVAT || cat.Retained || cat.Informative {
			continue
		}
		vat = vat.MatchPrecision(cat.Amount).Add(cat.Amount)
	}
	return vat
}

func sumTaxCharges(charges []*bill.Charge, taxTypes []cbc.Code) *num.Amount {
	var sum *num.Amount
	for _, c := range charges {
		if c == nil || !c.Key.Has(bill.ChargeKeyTax) {
			continue
		}
		if !c.Ext.Get(arca.ExtKeyTaxType).In(taxTypes...) {
			continue
		}
		if sum == nil {
			a := c.Amount
			sum = &a
		} else {
			a := sum.MatchPrecision(c.Amount).Add(c.Amount)
			sum = &a
		}
	}
	return sum
}

var _ = templruntime.GeneratedTemplate
