root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = ["serve", "-p", "3000", "--pdf", "prince"]
bin = "./gobl.html"
cmd = "templ generate && go build ./cmd/gobl.html"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata"]
exclude_file = ["gobl.html"]
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "yaml", "tpl", "templ", "css", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
enabled = false
app_port = 3000
proxy_port = 3001

[screen]
clear_on_rebuild = false
keep_scroll = true
